export const db = [
    {
        id: 1,
        name: 'Pranjal Sharma',
        img: 'https://res.cloudinary.com/dqhyudo4x/image/upload/v1695214158/WhatsApp_Image_2023-09-20_at_18.17.28-removebg-preview_aj0nue.png',
        age: 32,
        gender: 'Male',
        location: 'Palo Alto',
        link: 'https://example.com/pranjal-sharma',
        matchPercentage: 95,
    },
    {
        id: 2,
        name: 'John Doe',
        img: 'https://randomuser.me/api/portraits/men/1.jpg',
        age: 28,
        gender: 'Male',
        location: 'New York City',
        link: 'https://example.com/john-doe',
        matchPercentage: 90,
    },
    {
        id: 3,
        name: 'Jane Smith',
        img: 'https://randomuser.me/api/portraits/women/2.jpg',
        age: 35,
        gender: 'Female',
        location: 'Los Angeles',
        link: 'https://example.com/jane-smith',
        matchPercentage: 85,
    },
    {
        id: 4,
        name: 'Alex Johnson',
        img: 'https://randomuser.me/api/portraits/lego/3.jpg',
        age: 25,
        gender: 'Non-Binary',
        location: 'San Francisco',
        link: 'https://example.com/alex-johnson',
        matchPercentage: 78,
    },
    {
        id: 5,
        name: 'Emily Davis',
        img: 'https://randomuser.me/api/portraits/women/4.jpg',
        age: 30,
        gender: 'Female',
        location: 'Chicago',
        link: 'https://example.com/emily-davis',
        matchPercentage: 92,
    },
    {
        id: 6,
        name: 'Chris Williams',
        img: 'https://randomuser.me/api/portraits/men/5.jpg',
        age: 32,
        gender: 'Male',
        location: 'Seattle',
        link: 'https://example.com/chris-williams',
        matchPercentage: 88,
    },
    {
        id: 7,
        name: 'Olivia Rodriguez',
        img: 'https://randomuser.me/api/portraits/women/6.jpg',
        age: 27,
        gender: 'Female',
        location: 'Miami',
        link: 'https://example.com/olivia-rodriguez',
        matchPercentage: 95,
    },
    {
        id: 8,
        name: 'Daniel Lee',
        img: 'https://randomuser.me/api/portraits/men/7.jpg',
        age: 31,
        gender: 'Male',
        location: 'Austin',
        link: 'https://example.com/daniel-lee',
        matchPercentage: 80,
    },
    {
        id: 9,
        name: 'Sophia Chen',
        img: 'https://randomuser.me/api/portraits/women/8.jpg',
        age: 29,
        gender: 'Female',
        location: 'Denver',
        link: 'https://example.com/sophia-chen',
        matchPercentage: 88,
    },
    {
        id: 10,
        name: 'Michael Kim',
        img: 'https://randomuser.me/api/portraits/men/9.jpg',
        age: 34,
        gender: 'Male',
        location: 'Portland',
        link: 'https://example.com/michael-kim',
        matchPercentage: 75,
    },
    {
        id: 11,
        name: 'Ava Brown',
        img: 'https://randomuser.me/api/portraits/women/10.jpg',
        age: 26,
        gender: 'Female',
        location: 'Phoenix',
        link: 'https://example.com/ava-brown',
        matchPercentage: 85,
    },
    // Add more entries as needed
];
